### ISSUE TITLE
Buttom blocked when automation fails

### ISSUE THREAD

**Issue by jmbenedetto** [rileymd88/automation-trigger#21]
Hi, Riley.

First of all, thanks a lot for your extension. I is amazingly helpful.

I tried to use your extension to create a button that would run an extension. It does not seem to work. I created the extension, but the app where the button lives can be used by many people. 

Do you know if this use case is covered?

Thanks again

Best regards

**Comment by rileymd88** [comment]
Hi @jmbenedetto 

Multiple people can click the button and trigger automations. You will need to ensure that your automation run mode is set to triggered for the button to work. 

Kind regards,
Riley

**Comment by rileymd88** [comment]
Closing this issue - feel free to open it again if you can provide more information on the issue.

**Comment by jmbenedetto** [comment]
Hello, Riley.

Thanks a lot for your reply.

What I did to test.
1) Create an automation;
2) Create the button and link the automation;
3) Press the button (the automation runs);
4) Change the automation owner via QMC;
5) Press the button (the button stays locked but the automation does not trigger)ç

Would you be interested on a video meeting where I show you what happens?

**Comment by rileymd88** [comment]
Hi @jmbenedetto,

I believe this is a normal behavior of an automation as it will invalidate the user credentials once you switch the owner. Please look at the automation history and look to see what the error was. Most likely it will say something about the credentials not being valid and to change that the user that now owns the automation needs to open it up and reconfigure any connectors that are being used.
