### ISSUE TITLE
[Feature request] Do action after automation run

### ISSUE THREAD

**Issue by Verrou** [rileymd88/automation-trigger#28]
Hey @rileymd88 - thanks so much for this awesome ext. it is super useful!
Is there any chance you'd be able to add the ability to run additional sheet related actions after the automation has run? In my specific use-case I'd love to be able to clear all selection. Could this either be implemented similar to the URL redirect OR as a UI implemented setting (I'd imagine similar to the standard button chart behaviour?)
Thanks again for this, if you start up a buymeacofffee or any other means of supporting you I'll be first in the door!

**Comment by rileymd88** [comment]
Hi @Verrou,

Thanks for your feedback! I am not actively developing this extension any more as almost all of the functionality was implemented into the standard native button from Qlik. With the native button you should be able to set variable values before or after running an automation now. Here is an example: https://www.youtube.com/watch?v=hYER2nGKctM 

Also if you need to create a dialog like experience then I would suggest looking at the new layout container in the dashboard bundle to achieve that. 

Riley
